-- ============================================================================
-- SWIMyti: avisos del recinto y Dashboard comun a los colaboradores
-- ============================================================================
-- Por que existe:
--   1) El home de cada rol se dedujo hasta ahora de usuarios.id_rol, que es
--      arbitrario en un modelo multi-roles: la jefatura demo tiene 'enfermeria'
--      como rol principal y 'jefatura' acumulado, por lo que aterrizaba en
--      /dashboard en vez de su modulo de coordinacion. Un Dashboard comun
--      elimina esa dependencia: todos los colaboradores entran por el mismo lado.
--   2) Los avisos (noticias, feriados, fechas relevantes) son del recinto, no
--      de un rol, asi que viven en una tabla propia y no en un perfil.
--
-- Decision de seguridad, tomada antes de escribir la migracion:
--   NO hay firma criptografica. Se evaluo y se descarto a proposito: la
--   "firma" que usa el proyecto (firma_digital_hash) es un SHA-256 de
--   id + reloj + texto fijo, generado en el navegador, que cualquiera con la
--   sesion puede reproducir; no es prueba de nada. Una firma asimetrica real
--   (llave privada por profesional) no impide la mala fe, solo la registra,
--   y cuesta llave, cifrado, verificacion y friccion en cada firma. Lo que si
--   sirve para summation es exactamente lo que ya guarantee la ficha clinica:
--   inmutabilidad + autor + fecha. Eso es lo que se replica aca.
--
-- Alcance deliberadamente acotado: buzon de lectura para colaboradores.
-- No envia correos ni push (restriccion comercial en AGENTS.md: sin Edge
-- Functions mientras no exista cliente). Lo publica presencialmente quien
-- esta en el recinto.
--
-- Inmutabilidad: mismo patron que fichas_medicas y enmiendas_auditoria.
-- IMPORTANTE y a proposito: la proteccion real aqui son los TRIGGERS, no las
-- policies. En este proyecto postgres tiene rolbypassrls = true, asi que ni
-- FORCE ROW LEVEL SECURITY ni el rol dueno detienen a quien tenga ese rol.
-- Un trigger, en cambio, se ejecuta siempre. Por eso no hay policies de
-- UPDATE ni de DELETE en estas tablas: no existe siquiera el permiso de
-- intentarlo, y el trigger cierra la puerta por si acaso.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1) Tabla de avisos: append-only
-- ---------------------------------------------------------------------------
create table if not exists public.avisos_recinto (
  id_aviso         bigint generated by default as identity primary key,
  titulo           text        not null,
  cuerpo           text        not null,
  -- Vigencia. fecha_fin es opcional a proposito: sin fecha_fin el aviso es
  -- permanente; con fecha deja de mostrarse al vencer y el registro se
  -- conserva (nada se borra).
  fecha_inicio     date        not null default current_date,
  fecha_fin        date,
  -- Correccion: un aviso que reemplaza a otro. No modifica el anterior, solo
  -- declara que lo deja de mostrar. El original sigue legible.
  reemplaza_a      bigint      references public.avisos_recinto (id_aviso) on delete restrict,
  -- uuid, no bigint: usuarios.id_usuario es uuid (verificado en
  -- information_schema). Lo mismo que fichas_medicas.id_usuario_creador.
  id_usuario_autor uuid        not null references public.usuarios (id_usuario) on delete restrict,
  created_at       timestamptz not null default now(),

  constraint avisos_recinto_vigencia_chk
    check (fecha_fin is null or fecha_fin >= fecha_inicio),

  -- El titulo es lo que se lee en la lista del Dashboard. Acotarlo evita que
  -- un aviso se trunque sin que nadie lo note.
  constraint avisos_recinto_titulo_chk
    check (char_length(btrim(titulo)) between 3 and 120),

  constraint avisos_recinto_cuerpo_chk
    check (char_length(btrim(cuerpo)) between 1 and 4000),

  -- Un aviso no puede reemplazarse a si mismo.
  constraint avisos_recinto_no_autoreemplazo_chk
    check (reemplaza_a is null or reemplaza_a <> id_aviso)
);

comment on table public.avisos_recinto is
  'Avisos del recinto (noticias, feriados, fechas relevantes) del Dashboard comun. Append-only.';
comment on column public.avisos_recinto.reemplaza_a is
  'Aviso que este corrige o reemplaza. El original no se modifica ni se borra.';
comment on column public.avisos_recinto.fecha_fin is
  'Vigencia. NULL = permanente. Al vencer deja de mostrarse sin borrarse.';

-- ---------------------------------------------------------------------------
-- 2) Tabla de retiros: append-only
-- ---------------------------------------------------------------------------
-- Retirar un aviso es un HECHO ("el 14 se decidió no atender"), asi que se
-- registra como un hecho mas y no como una mutacion del aviso. Es el mismo
-- patron que enmiendas_auditoria sobre fichas_medicas: la anotacion va en su
-- propia tabla y la original queda intacta.
create table if not exists public.avisos_retiro (
  id_retiro        bigint generated by default as identity primary key,
  id_aviso         bigint      not null references public.avisos_recinto (id_aviso) on delete restrict,
  motivo           text        not null,
  id_usuario_autor uuid        not null references public.usuarios (id_usuario) on delete restrict,
  created_at       timestamptz not null default now(),

  constraint avisos_retiro_motivo_chk
    check (char_length(btrim(motivo)) between 3 and 500),

  -- Un aviso no se retira dos veces. El indice unico hace valer la regla en
  -- la base, no en el formulario: dos clics rapidos no pueden dejar dos
  -- retiros contradictorios.
  constraint avisos_retiro_unico_uniq unique (id_aviso)
);

comment on table public.avisos_retiro is
  'Retiros de avisos. Append-only: el retiro es un registro, no una mutacion.';

-- ---------------------------------------------------------------------------
-- 3) Inmutabilidad
-- ---------------------------------------------------------------------------
-- Variante propia del trigger generico: el mensaje de
-- fn_bloquear_mutacion_inmutable dice "Use enmiendas_auditoria", que no es el
-- remedio de un aviso (aca es Retire o publique uno que lo reemplace). Se
-- duplica la funcion en vez de tocar la de la ficha clinica para no modificar
-- la ruta sensible desde un feature de avisos.
create or replace function public.fn_bloquear_mutacion_inmutable_avisos()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  raise exception
    'SWIMyti: la tabla %.% es inmutable (append-only). Operacion % no permitida. Para dejar de mostrar un aviso, registre el retiro o publique uno que lo reemplace.',
    tg_table_schema, tg_table_name, tg_op
    using errcode = '42501';
  return null;
end;
$$;

drop trigger if exists trg_avisos_recinto_no_update on public.avisos_recinto;
create trigger trg_avisos_recinto_no_update
  before update on public.avisos_recinto
  for each row execute function public.fn_bloquear_mutacion_inmutable_avisos();

drop trigger if exists trg_avisos_recinto_no_delete on public.avisos_recinto;
create trigger trg_avisos_recinto_no_delete
  before delete on public.avisos_recinto
  for each row execute function public.fn_bloquear_mutacion_inmutable_avisos();

drop trigger if exists trg_avisos_retiro_no_update on public.avisos_retiro;
create trigger trg_avisos_retiro_no_update
  before update on public.avisos_retiro
  for each row execute function public.fn_bloquear_mutacion_inmutable_avisos();

drop trigger if exists trg_avisos_retiro_no_delete on public.avisos_retiro;
create trigger trg_avisos_retiro_no_delete
  before delete on public.avisos_retiro
  for each row execute function public.fn_bloquear_mutacion_inmutable_avisos();

-- ---------------------------------------------------------------------------
-- 4) El autor no se inventa y no se cambia
-- ---------------------------------------------------------------------------
-- Trigger, y no policy, porque RLS decide QUE FILAS, nunca QUE COLUMNAS: no
-- hay forma de "forzar" una columna desde una policy. Con esto, un cliente no
-- puede publicar un aviso haciendose pasar por el administrador.
--
-- security invoker a proposito: solo escribe new.<columna>, no toca otra
-- tabla, asi que no necesita el privilegio extra de SECURITY DEFINER.
-- En UPDATE y DELETE el trigger de inmutabilidad ya aborta antes.
create or replace function public.fn_avisos_autor()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'SWIMyti: no hay sesion para registrar el aviso';
  end if;
  new.id_usuario_autor := auth.uid();
  return new;
end;
$$;

drop trigger if exists trg_avisos_recinto_autor on public.avisos_recinto;
create trigger trg_avisos_recinto_autor
  before insert on public.avisos_recinto
  for each row execute function public.fn_avisos_autor();

drop trigger if exists trg_avisos_retiro_autor on public.avisos_retiro;
create trigger trg_avisos_retiro_autor
  before insert on public.avisos_retiro
  for each row execute function public.fn_avisos_autor();

-- ---------------------------------------------------------------------------
-- 5) Indices
-- ---------------------------------------------------------------------------
-- El Dashboard lee avisos vigentes y no retirados. Es el unico patron de
-- lectura, asi que los indices van ahi y no a la inversa.
create index if not exists idx_avisos_recinto_vigencia
  on public.avisos_recinto (fecha_inicio desc, id_aviso desc);

create index if not exists idx_avisos_recinto_reemplaza
  on public.avisos_recinto (reemplaza_a)
  where reemplaza_a is not null;

create index if not exists idx_avisos_retiro_aviso
  on public.avisos_retiro (id_aviso);

-- ---------------------------------------------------------------------------
-- 6) RLS
-- ---------------------------------------------------------------------------
alter table public.avisos_recinto enable row level security;
alter table public.avisos_recinto force row level security;

alter table public.avisos_retiro enable row level security;
alter table public.avisos_retiro force row level security;

-- NO se crean policies de UPDATE ni de DELETE en ninguna de las dos tablas.
-- Sin policy no hay permiso, y el trigger de inmutabilidad cierra la puerta.

-- Lectura: colaboradores. NO se usa fn_es_staff() a proposito, por dos motivos
-- verificados en 20260812000000_initial_schema.sql:325:
--   1) su lista no incluye 'jefatura', asi que una jefatura con rol principal
--      'jefatura' no podria ni leer el Dashboard;
--   2) evalua con fn_rol_actual() (rol principal), no con el conjunto de
--      roles, que es el mismo defecto que hacia impredecible el home.
-- Se declara el conjunto de colaboradores explicito con fn_tiene_rol, que si
-- evalua la union. Los roles nuevos habran que sumarlos aqui a proposito:
-- un aviso del recinto solo tiene sentido para alguien del recinto.
create policy "SWIMyti: avisos legibles por colaboradores"
  on public.avisos_recinto
  for select
  to authenticated
  using (fn_tiene_rol(
    array[
      'administrador', 'administrativo', 'doctor',
      'enfermeria', 'jefatura', 'unidad_apoyo'
    ]::text[]
  ));

create policy "SWIMyti: retiros legibles por colaboradores"
  on public.avisos_retiro
  for select
  to authenticated
  using (fn_tiene_rol(
    array[
      'administrador', 'administrativo', 'doctor',
      'enfermeria', 'jefatura', 'unidad_apoyo'
    ]::text[]
  ));

-- Escritura: administrador y jefatura (los dos coordinan; el usuario decidio
-- que ambos publiquen).
create policy "SWIMyti: avisos publicables por administrador o jefatura"
  on public.avisos_recinto
  for insert
  to authenticated
  with check (fn_tiene_rol(array['administrador', 'jefatura']::text[]));

create policy "SWIMyti: retiros registrables por administrador o jefatura"
  on public.avisos_retiro
  for insert
  to authenticated
  with check (fn_tiene_rol(array['administrador', 'jefatura']::text[]));

-- ---------------------------------------------------------------------------
-- 7) Permisos de tabla
-- ---------------------------------------------------------------------------
-- select + insert, nada mas. No se otorga update ni delete a nadie.
grant select, insert on public.avisos_recinto to authenticated;
grant select, insert on public.avisos_retiro to authenticated;

revoke all on public.avisos_recinto from anon, public;
revoke all on public.avisos_retiro from anon, public;

comment on policy "SWIMyti: avisos legibles por colaboradores"
  on public.avisos_recinto is
  'Solo colaboradores: el paciente no lee avisos del recinto (su modulo es el Portal).';
comment on policy "SWIMyti: avisos publicables por administrador o jefatura"
  on public.avisos_recinto is
  'Administrador y jefatura publican. No hay policy de update ni de delete: los avisos son append-only.';
comment on policy "SWIMyti: retiros legibles por colaboradores"
  on public.avisos_retiro is
  'Solo colaboradores. El historial de retiros es parte de la trazabilidad.';
comment on policy "SWIMyti: retiros registrables por administrador o jefatura"
  on public.avisos_retiro is
  'Administrador y jefatura registran el retiro de un aviso, con su motivo.';
