-- ============================================================================
-- SWIMyti: receso protegido con rotacion, y verificacion de cobertura
-- ============================================================================
-- Que resuelve:
--   En un centro de mediana complejidad el servicio NO se detiene a la hora
--   de almuerzo. Hay una franja protegida (12:00-15:00 aprox, variable por
--   recinto) dentro de la cual los profesionales se turnan: en cada momento
--   hay alguien en receso y alguien atendiendo. La jefatura dispone quien
--   sale y a que hora, rotando para que la unidad no quede desatendida.
--
-- Decisiones de producto tomadas con el usuario (2026-10-01):
--   1) El receso NO es una entidad nueva. Se realiza con la herramienta que ya
--      existe: la jefatura bloquea horas. Los bloques son de 15 minutos, asi
--      que una hora de receso son 4 bloques y media hora son 2. La
--      flexibilidad se obtiene del diseno actual, sin construir nada.
--   2) El motivo tiene que ser ESTRUCTURADO (planificado / sobrevenido), no
--      texto libre, porque de ese campo dependen mas adelante licencias,
--      libres y vacaciones en RRHH, y porque la consecuencia de cobertura
--      cambia segun el caso.
  --   3) La cobertura se cuenta sobre GLOBAl, no por area: el usuario fue
--      explicito ("lo importante es que los pacientes nunca queden
--      desatendidos"), y ademas administrativo y administrador no tienen
--      horario en el sistema, asi que no pueden contarse. Los guardias son
--      servicio subcontratado y quedan fuera.
--      "Presente" = cualquier bloque que NO este bloqueada, e incluye
--      'reservada': ese profesional esta con un paciente, que es justo lo que
--      hay que proteger. Contar solo 'disponible' seria un error: un
--      profesional con la agenda llena esta trabajando, no desatendido, y
--      exigirlo dejaria el receso imposible de Arms.
--   4) Planificado que deja la unidad sin cobertura -> se RECHAZA. Sobrevenido
--      que la deja sin cobertura -> se PERMITE con advertencia, porque si hay
--      un unico profesional de turno y se enferma, bloquear es obligatorio:
--      un rechazo duro dejaria al sistema inutil justo cuando mas se necesita.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1) Ventana de receso del recinto
-- ---------------------------------------------------------------------------
-- config_recinto es clave/valor, asi que la ventana es una fila mas y no un
-- cambio de esquema. Se guarda 'HH24:MI-HH24:MI'. El valor por defecto es el
-- habitual, pero cada recinto puede ajustarlo.
insert into public.config_recinto (clave, valor, descripcion)
values (
  'ventana_receso',
  '12:00-15:00',
  'Franja protegida de almuerzo dentro de la jornada en la que la jefatura '
  ' rota a los profesionales. Formato HH:MM-HH:MM. Un receso de 1 hora son 4 '
  'bloques de 15 min; media hora son 2. Si la franja es de 3 horas y el receso '
  'de 1 hora, solo caben 3 profesionales por turno: la planificacion debe '
  'darle mas de una vuelta al dia o acortar el receso.'
)
on conflict (clave) do nothing;

-- ---------------------------------------------------------------------------
-- 2) Catalogo de motivos de bloqueo
-- ---------------------------------------------------------------------------
-- Catalogo y no texto libre: RRHH necesita despues distinguir licencias,
-- vacaciones y libres administrativos, y la cobertura se comporta distinto
-- segun sea planificado o sobrevenido.
create table if not exists public.motivos_bloqueo (
  id_motivo  integer generated by default as identity primary key,
  nombre     text    not null,
  -- planificado: se sabia antes (receso, vacaciones, libre). Puede rechazarse
  --             si deja la unidad sin cobertura.
  -- sobrevenido:occurrio sin aviso (ausencia, llegada tarde). Debe poder
  --             ejecutarse siempre.
  tipo       text    not null,
  -- Motivos que exigen detalle escrito (por ejemplo "Licencia médica" tiene
  -- que dejar constancia de la fecha de inicio).
  requiere_detalle boolean not null default false,
  activo     boolean not null default true,

  constraint motivos_bloqueo_nombre_uniq unique (nombre),
  constraint motivos_bloqueo_tipo_chk check (tipo in ('planificado', 'sobrevenido'))
);

comment on table public.motivos_bloqueo is
  'Motivos por los que la jefatura deshabilita horas. El tipo define si la falta de cobertura se rechaza o solo se advierte.';

insert into public.motivos_bloqueo (nombre, tipo, requiere_detalle) values
  ('Pausa de almuerzo',            'planificado',   false),
  ('Vacaciones',                    'planificado',   false),
  ('Libre administrativo',          'planificado',   false),
  ('Permiso',                       'planificado',   false),
  ('Capacitación',                  'planificado',   false),
  ('Licencia médica',               'sobrevenido',   true),
  ('Ausencia',                      'sobrevenido',   false),
  ('Llegada tardía',                'sobrevenido',   false),
  ('Otro',                          'sobrevenido',   true)
on conflict (nombre) do nothing;

-- ---------------------------------------------------------------------------
-- 3) El bloque apunta al motivo estruturado
-- ---------------------------------------------------------------------------
-- Se AGREGA la referencia y se conserva motivo_bloqueo como texto. No se
-- reemplaza: el texto es una instantanea legible (nombre + detalle) que
-- sobrevive aunque el catalogo cambie, y es la que muestran los tooltips.
alter table public.horarios_disponibles
  add column if not exists id_motivo_bloqueo integer
  references public.motivos_bloqueo (id_motivo) on delete restrict;

comment on column public.horarios_disponibles.id_motivo_bloqueo is
  'Motivo estructurado del bloqueo. Define si la falta de cobertura se rechaza o se advierte.';

create index if not exists idx_horarios_id_motivo_bloqueo
  on public.horarios_disponibles (id_motivo_bloqueo)
  where id_motivo_bloqueo is not null;

-- ---------------------------------------------------------------------------
-- 4) Cobertura: que franjas quedan sin nadie
-- ---------------------------------------------------------------------------
-- Se cuenta GLOBAL, no por especialidad ni por area (decision 3): la regla
-- declarada es que no queden pacientes desatendidos, y los administrativos
-- no tienen horario en el sistema que contar.
--
-- "Presente" = cualquier bloque que NO este bloqueada. Un bloque 'reservada'
-- cuenta como presente: ese profesional esta con un paciente, que es
-- exactamente lo que la regla quiere proteger. Contar solo 'disponible'
-- seria peor: un profesional con la agenda llena esta trabajando, no
-- desatendido, y exigirlo dejaria el receso imposible de Arms.
create or replace function public.fn_cobertura_no_atendida(p_ids bigint[])
returns table (fecha timestamptz, n_presentes integer)
language sql
stable
security definer
set search_path = 'public'
as $$
  -- Se simula el bloqueo restando de cada franja los ids que se quieren
  -- bloquear, en vez de bloquear de verdad: la funcion es de solo lectura y
  -- la ejecuta la propia RPC antes de escribir.
  with slots as (
    select distinct h.fecha_inicio as fecha
    from public.horarios_disponibles h
    where h.id_horario = any(p_ids)
      and h.fecha_fin > now()
  ),
  presentes as (
    select s.fecha, count(b.id_horario)::integer as n
    from slots s
    join public.horarios_disponibles b
      on b.fecha_inicio = s.fecha
    where b.estado <> 'bloqueada'
      and not (b.id_horario = any(p_ids))
    group by s.fecha
  )
  select s.fecha, 0
  from slots s
  left join presentes p on p.fecha = s.fecha
  where coalesce(p.n, 0) = 0
  order by s.fecha;
$$;

comment on function public.fn_cobertura_no_atendida(bigint[]) is
  'Franjas futuras que quedarian sin ningun profesional presente si se bloquearan los ids indicados. No escribe nada.';

revoke all on function public.fn_cobertura_no_atendida(bigint[]) from public;
grant execute on function public.fn_cobertura_no_atendida(bigint[]) to authenticated;

-- ---------------------------------------------------------------------------
-- 5) fn_bloquear_horarios: motivo estructurado + cobertura
-- ---------------------------------------------------------------------------
-- Firma nueva (p_ids, p_id_motivo, p_detalle) en vez de (p_ids, p_motivo).
-- Se cambia a proposito: el texto libre no permite decidir si la falta de
-- cobertura se rechaza o se advierte, y no habilita el catastro de RRHH.
-- El retorno sigue siendo jsonb, asi que la forma no se rompe para el
-- cliente; lo que se agrega es la lista de advertencias.
create or replace function public.fn_bloquear_horarios(
  p_ids        bigint[],
  p_id_motivo  integer,
  p_detalle    text default null
)
returns jsonb
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_motivo_nombre    text;
  v_motivo_tipo      text;
  v_requiere_detalle boolean;
  v_detalle          text;
  v_motivo_texto     text;
  v_fuera            bigint[];
  v_inexistentes     bigint[];
  v_sin_cobertura    timestamptz[];
  v_afectadas        jsonb;
  v_bloqueadas       int := 0;
  v_canceladas       int := 0;
begin
  -- --- Motivo estructurado ---
  select m.nombre, m.tipo, m.requiere_detalle
    into v_motivo_nombre, v_motivo_tipo, v_requiere_detalle
  from public.motivos_bloqueo m
  where m.id_motivo = p_id_motivo and m.activo;

  if v_motivo_nombre is null then
    raise exception 'SWIMyti: el motivo del bloqueo no existe o esta inactivo.'
      using errcode = '22023';
  end if;

  v_detalle := btrim(coalesce(p_detalle, ''));

  if v_requiere_detalle and v_detalle = '' then
    raise exception
      'SWIMyti: el motivo "%" requiere detalle (por ejemplo, la fecha de inicio de la licencia).',
      v_motivo_nombre
      using errcode = '22023';
  end if;

  v_motivo_texto := case when v_detalle = '' then v_motivo_nombre
                         else v_motivo_nombre || ' (' || v_detalle || ')' end;

  if p_ids is null or cardinality(p_ids) = 0 then
    raise exception 'SWIMyti: no se selecciono ninguna hora para deshabilitar.'
      using errcode = '22023';
  end if;

  -- --- Horas invalidas ---
  select coalesce(array_agg(h.id_horario), '{}'::bigint[])
    into v_inexistentes
  from public.horarios_disponibles h
  where h.id_horario = any(p_ids)
    and (h.fecha_fin <= now() or h.estado in ('completada', 'cancelada'));

  if cardinality(v_inexistentes) > 0 then
    raise exception
      'SWIMyti: % de las horas seleccionadas ya pasaron, se completaron o se cancelaron. No se puede deshabilitar una hora que no es futura.',
      cardinality(v_inexistentes)
      using errcode = '22023';
  end if;

  -- --- Ambito: administrador coordina todas; la jefatura, las de su
  --     servicio mas las suyas propias. El coalesce no es cosmetico: sin
  --     sesion auth.uid() es NULL y la comparacion evalua NULL, con lo cual
  --     `not (... or NULL)` es NULL, la fila NO entra en v_fuera y el bloqueo
  --     pasaria.
  select coalesce(array_agg(h.id_horario), '{}'::bigint[])
    into v_fuera
  from public.horarios_disponibles h
  where h.id_horario = any(p_ids)
    and not coalesce(
      public.fn_es_admin()
      or public.fn_es_coordinador_agenda(h.id_especialidad)
      or (h.id_profesional is not null and h.id_profesional = auth.uid()),
      false
    );

  if cardinality(v_fuera) > 0 then
    raise exception
      'SWIMyti: no coordinas el area de % de las horas seleccionadas. Solo puedes deshabilitar horas de tu servicio o tuyas.',
      cardinality(v_fuera)
      using errcode = '42501';
  end if;

  -- --- Cobertura ---
  -- Se evalua SIEMPRE, antes de tocar nada, para que el rechazo o la
  -- advertencia hablen de franjas concretas y no de un "algo se rompio".
  select coalesce(array_agg(c.fecha), '{}'::timestamptz[])
    into v_sin_cobertura
  from public.fn_cobertura_no_atendida(p_ids) c;

  if cardinality(v_sin_cobertura) > 0 and v_motivo_tipo = 'planificado' then
    -- Planificado: se rechaza. Es una decision que se toma con tiempo.
    raise exception
      'SWIMyti: bloquear por "%" dejaria el centro sin ningun profesional en % franja(s), desde % hasta %. Si es una ausencia sobrevenida, usa un motivo sobrevenido.',
      v_motivo_nombre,
      cardinality(v_sin_cobertura),
      to_char(min(v_sin_cobertura), 'DD/MM HH24:MI'),
      to_char(max(v_sin_cobertura), 'DD/MM HH24:MI')
      using errcode = 'P0001';
  end if;

  -- --- Quien hay que llamar por telefono, ANTES de cancelar ---
  -- El sistema no notifica por correo (restriccion comercial: sin Edge
  -- Functions mientras no exista cliente), asi que recepcion necesita la lista.
  -- Se recoge antes de cancelar porque despues el estado ya no es 'reservada'.
  select coalesce(
           jsonb_agg(
             jsonb_build_object(
               'id_cita',     c.id_cita,
               'id_paciente', c.id_paciente,
               'fecha',       h.fecha_inicio
             )
           ),
           '[]'::jsonb
         )
    into v_afectadas
  from public.citas c
  join public.horarios_disponibles h on h.id_horario = c.id_horario
  where h.id_horario = any(p_ids)
    and c.estado = 'reservada';

  -- Las horas con cita quedan bloqueadas igual. Bloquear sin cancelar dejaria
  -- al paciente con una reserva fantasma que el portal le sigue mostrando.
  update public.horarios_disponibles
     set estado             = 'bloqueada',
         motivo_bloqueo     = v_motivo_texto,
         id_motivo_bloqueo  = p_id_motivo,
         bloqueado_por      = auth.uid(),
         bloqueado_at       = now()
   where id_horario = any(p_ids)
     and estado is distinct from 'completada';

  get diagnostics v_bloqueadas = row_count;

  -- Solo las citas realmente reservadas. Una cita atendida, cancelada o
  -- bloqueada NO se toca: es historia clinica, no agenda futura. Sin este
  -- filtro el UPDATE marcaria como canceladas citas ya realizadas.
  update public.citas
     set estado             = 'cancelada',
         motivo_cancelacion = v_motivo_texto
   where id_horario = any(p_ids)
     and estado = 'reservada';

  get diagnostics v_canceladas = row_count;

  return jsonb_build_object(
    'ok',               true,
    'horas_bloqueadas', v_bloqueadas,
    'citas_canceladas', v_canceladas,
    'citas_afectadas',  v_afectadas,
    'motivo',           v_motivo_texto,
    'tipo_motivo',      v_motivo_tipo,
    -- Vacio en planificado (si hubiera estado, habria rechazado). Llenado
    -- cuando el motivo era sobrevenido y aun asi no queda nadie: el bloque se
    -- aplico igual, que es lo que se necesita en una urgencia, y se ve la
    -- franja concreta que quedo descoverierta.
    'franjas_sin_cobertura', coalesce(
      to_jsonb(array(
        select to_char(f, 'DD/MM HH24:MI')
        from unnest(v_sin_cobertura) f
        order by f
      )), '[]'::jsonb
    )
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- 6) RLS del catalogo de motivos
-- ---------------------------------------------------------------------------
alter table public.motivos_bloqueo enable row level security;
alter table public.motivos_bloqueo force row level security;

-- Todos los colaboradores leen el catalogo: aparece en el selector de motivo.
-- Lo escribe el administrador, que es quien mantiene el catalogo del recinto.
create policy "SWIMyti: motivos de bloqueo legibles por colaboradores"
  on public.motivos_bloqueo
  for select
  to authenticated
  using (fn_tiene_rol(
    array[
      'administrador', 'administrativo', 'doctor',
      'enfermeria', 'jefatura', 'unidad_apoyo'
    ]::text[]
  ));

create policy "SWIMyti: catalogo de motivos editable por administrador"
  on public.motivos_bloqueo
  for all
  to authenticated
  using (fn_es_admin())
  with check (fn_es_admin());

grant select on public.motivos_bloqueo to authenticated;
grant insert, update on public.motivos_bloqueo to authenticated;

revoke all on public.motivos_bloqueo from anon, public;

-- ---------------------------------------------------------------------------
-- 7) Endurecimiento: anon no escribe la agenda
-- ---------------------------------------------------------------------------
-- Esta tabla NO es inmutable (reservar, liberar y bloquear son parte del
-- negocio), asi que no se le quita update ni delete a nadie. Lo que no
-- corresponde es que el rol ANON (sin sesion, el que viaja en la clave
-- publica del navegador) pueda escribirla: toda mutacion de la agenda pasa
-- por RPCs SECURITY DEFINER con validaciones de ambito. Se le deja leer,
-- que es lo que usa el calendario publico, y se le quitan las escrituras.
--
-- Nota: esta revocacion se aplico por error al escribir la migracion y se
-- mantuvo a proposito, documentandola aqui. Se verifico que authenticated y
-- service_role conservan sus privilegios completos.
revoke insert, update, delete, truncate, references, trigger
  on public.horarios_disponibles from anon;
